FROM continuumio/miniconda3
RUN apt-get update
RUN apt-get install -y build-essential zlib1g zlib1g-dev
RUN apt-get install -y libbz2-dev
RUN mkdir /opt/build
COPY docker_dev/install_with_conda.sh /opt/build
COPY src/ /opt/build/src/
COPY falcon/ /opt/build/falcon/
COPY py/ /opt/build/py/
COPY ksw2/ /opt/build/ksw2/
RUN cd /opt/build; bash install_with_conda.sh
RUN . /opt/conda/bin/activate; conda clean -all
RUN apt-get update
RUN apt-get install -y parallel time
RUN . /opt/conda/bin/activate; conda activate peregrine;
RUN apt-get install -y make
RUN mkdir /opt/licenses
COPY LICENSE /opt/licenses/LICENSE
COPY LICENSE.falcon /opt/licenses/LICENSE.falcon
COPY LICENSE.minimap2 /opt/licenses/LICENSE.minimap2
RUN mkdir /opt/test
COPY docker_dev/test/Makefile /opt/test
COPY docker_dev/test/run_test.sh /opt/test
COPY docker_dev/test/simulate_reads.py /opt/test
COPY docker_dev/bashrc /root/.bashrc
COPY docker_dev/entry.sh /opt/
COPY docker_dev/entry_dev.sh /opt/
COPY docker_dev/jupyterlab.sh /opt/
WORKDIR /opt/test
ENTRYPOINT ["/opt/entry_dev.sh"]
