name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v1
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - name: Install dependencies
        run: |
          CONDAROOT=/usr/share/miniconda && bash ./install_with_conda.sh
        shell: bash
      - name: Functional testing
        run: |
          bash ./test/functional_tests.sh
        shell: bash
      - name: Unit testing
        run: |
          . /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate peregrine
          CONDAROOT=/usr/share/miniconda && bash ./install_with_conda.sh
          python3 -m pip install pytest
          pytest test/
        shell: bash
